name: Build Rust Doc And Run tests

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2024-01-18

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.rust_toolchain }}
          components: rust-src, llvm-tools-preview
          target: riscv64gc-unknown-none-elf
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      # - name: Cache QEMU
      #   uses: actions/cache@v3
      #   with:
      #     path: qemu-7.0.0
      #     key: qemu-7.0.0-x86_64-riscv64
      # - name: Install QEMU
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install ninja-build -y
      #     if [ ! -d qemu-7.0.0 ]; then
      #       wget https://download.qemu.org/qemu-7.0.0.tar.xz
      #       tar -xf qemu-7.0.0.tar.xz
      #     fi
      #     cd qemu-7.0.0
      #     ./configure --target-list=riscv64-softmmu
      #     make -j
      #     sudo make install
      #     qemu-system-riscv64 --version
      - name: Test Build riscv64
        run: cd os && make ARCH=riscv64 build
      - name: Test Build aarch64
        run: cd os && make ARCH=aarch64 build
      - name: Test Build x86_64
        run: cd os && make ARCH=x86_64 build
      - name: Test Build loongarch64
        run: cd os && make ARCH=loongarch64 build
        # run: cd os && make run TEST=1
        # timeout-minutes: 10
      
